
n0.exe: MACROS = -D KETA='(1200/RADIX_LEN)'
n0.exe: ../integer.c ../integer.h n0.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n0-integer.o
	gcc -O3 $(MACROS) -I.. n0-integer.o n0.c -o n0.exe

n1.exe: MACROS = -D KETA='(1200/RADIX_LEN)'
n1.exe: ../integer.c ../integer.h n1.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n1-integer.o
	gcc -O3 $(MACROS) -I.. n1-integer.o n1.c -o n1.exe

n2.exe: MACROS = -D KETA='(1200/RADIX_LEN)'
n2.exe: ../integer.c ../integer.h n2.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n2-integer.o
	gcc -O3 $(MACROS) -I.. n2-integer.o n2.c -o n2.exe

n3.exe: MACROS = -D KETA='(1200/RADIX_LEN)'
n3.exe: ../integer.c ../integer.h n3.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n3-integer.o
	gcc -O3 $(MACROS) -I.. n3-integer.o n3.c -o n3.exe

n4.exe: MACROS  = -D KETA='(3570/RADIX_LEN+10)'
n4.exe: ../integer.c ../integer.h n4.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n4-integer.o
	gcc -O3 $(MACROS) -I.. n4-integer.o n4.c -o n4.exe

n5.exe: MACROS = -D KETA='(2010/RADIX_LEN+10)'
n5.exe: ../integer.c ../integer.h n5.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n5-integer.o
	gcc -O3 $(MACROS) -I.. n5-integer.o n5.c -o n5.exe

n6.exe: MACROS = -D KETA='(2000/RADIX_LEN+10)'
n6.exe: ../integer.c ../integer.h n6.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n6-integer.o
	gcc -O3 $(MACROS) -I.. n6-integer.o n6.c -o n6.exe

n7.exe: MACROS = -D KETA='(1100/RADIX_LEN+10)'
n7.exe: ../integer.c ../integer.h n7.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n7-integer.o
	gcc -O3 $(MACROS) -I.. n7-integer.o n7.c -o n7.exe

n8.exe: MACROS = -D KETA='(30/RADIX_LEN)'
n8.exe: ../integer.c ../integer.h n8.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n8-integer.o
	gcc -O3 $(MACROS) -I.. n8-integer.o n8.c -o n8.exe

n9.exe: MACROS = -D KETA='(1100/RADIX_LEN+10)'
n9.exe: ../integer.c ../integer.h n9.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n9-integer.o
	gcc -O3 $(MACROS) -I.. n9-integer.o n9.c -o n9.exe

n10.exe: MACROS = -D KETA='(30/RADIX_LEN)'
n10.exe: ../integer.c ../integer.h n10.c Makefile
	gcc -O3 $(MACROS) -c ../integer.c -o n10-integer.o
	gcc -O3 $(MACROS) -I.. n10-integer.o n10.c -o n10.exe
